### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by Zomba4okk** [Zomba4okk/DjangoOnlinerLikeShop#11]
- [x] Add main structure of django project (without any specific apps). Project root should contain a specific folder for all apps. Configuration folder (that stores urls, settings, and middleware configs) should be named "config";
- [x] All environment variables (e.g. DB host and port )should be moved to a separate .env file, which will not be pushed in the repository (for security reasons);
- [x] Setup postgres as project DB;
- [x] Add docker-compose file to run environment locally;
- [x] Add requirements file.

**Comment by borisoid** [comment]
Since it's just a training project with <b>no <i>real</i> concern about security</b>, it's ok leave .env variables here.


SECRET_KEY='7@w(y=8#)occpjz4w%k!z8v_@l2h)a+3&152m69iex3tsg1+wz'

db_server_host=127.0.0.1
db_server_port=5432
db_name=onliner_db
db_user=onliner_user
db_password=onliner_password
